--[[
    2020 Xalalau Xubilozo. MIT License
    https://xalalau.com/
--]]

TPC.version = "Pre 1.0"

TPC.defaultPreset = "Saara"

TPC.colors = {
    GMod = {
        bright = true,
        dark = true,
        font = true
    },
    Addon = {
        bright = true,
        dark = true,
        font = true
    },
    Highlight = {
        bright = true,
        dark = true,
        font = true
    }
}

-- ["panel"] = true
TPC.highlights = {}

TPC.fakeToolPanelList = {
    GMod = {
        dark = {},
        bright = {}
    },
    Addon = {
        dark = {},
        bright = {}
    },
    Highlight = {
        dark = {},
        bright = {}
    }
}

-- { "toolType", "toolName", "highlight" or nil }
TPC.fakeToolList = {
    { "GMod", "Axis" },
    { "GMod", "Ball Socket" },
    { "GMod", "Elastic" },
    { "GMod", "Hydraulic" },
    { "GMod", "Motor" },
    { "GMod", "Slider" },
    { "GMod", "Weld", "highlight" },
    { "Addon", "Addon Tool 1" },
    { "Addon", "Addon Tool 2" },
    { "GMod", "Muscle" },
    { "GMod", "Pulley", "highlight" },
    { "Addon", "Addon Tool 3", "highlight" },
    { "GMod", "Rope" },
    { "Addon", "Addon Tool 4" },
    { "Addon", "Addon Tool 5" },
    { "Addon", "Addon Tool 6" },
    { "Addon", "Addon Tool 7" },
    { "Addon", "Addon Tool 8", "highlight" },
    { "Addon", "Addon Tool 9" }
}

TPC.defaultTools = {
    ["axis"] = true,
    ["ballsocket"] = true,
    ["elastic"] = true,
    ["hydraulic"] = true,
    ["motor"] = true,
    ["muscle"] = true,
    ["pulley"] = true,
    ["rope"] = true,
    ["slider"] = true,
    ["weld"] = true,
    ["winch"] = true,
    ["balloon"] = true,
    ["button"] = true,
    ["duplicator"] = true,
    ["dynamite"] = true,
    ["emitter"] = true,
    ["hoverball"] = true,
    ["lamp"] = true,
    ["light"] = true,
    ["nocollide"] = true,
    ["physprop"] = true,
    ["remover"] = true,
    ["thruster"] = true,
    ["wheel"] = true,
    ["eyeposer"] = true,
    ["faceposer"] = true,
    ["finger"] = true,
    ["inflator"] = true,
    ["camera"] = true,
    ["colour"] = true,
    ["material"] = true,
    ["paint"] = true,
    ["trails"] = true
}

TPC.presets = {
    ["[Default]"] = {
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_font_r = "135",
        tpc_gmod_font_g = "135",
        tpc_gmod_font_b = "135",
        tpc_gmod_font_a = "255",
        tpc_addon_dark_r = "255",
        tpc_addon_dark_g = "255",
        tpc_addon_dark_b = "255",
        tpc_addon_dark_a = "255",
        tpc_addon_bright_r = "255",
        tpc_addon_bright_g = "255",
        tpc_addon_bright_b = "255",
        tpc_addon_bright_a = "255",
        tpc_addon_font_r = "135",
        tpc_addon_font_g = "135",
        tpc_addon_font_b = "135",
        tpc_addon_font_a = "255",
        tpc_highlight_dark_r = "255",
        tpc_highlight_dark_g = "255",
        tpc_highlight_dark_b = "255",
        tpc_highlight_dark_a = "255",
        tpc_highlight_bright_r = "255",
        tpc_highlight_bright_g = "255",
        tpc_highlight_bright_b = "255",
        tpc_highlight_bright_a = "255",
        tpc_highlight_font_r = "227",
        tpc_highlight_font_g = "0",
        tpc_highlight_font_b = "0",
        tpc_highlight_font_a = "255"
    },
    ["BSDO"] = {
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_font_r = "135",
        tpc_gmod_font_g = "135",
        tpc_gmod_font_b = "135",
        tpc_gmod_font_a = "255",
        tpc_addon_dark_r = "95",
        tpc_addon_dark_g = "227",
        tpc_addon_dark_b = "220",
        tpc_addon_dark_a = "85",
        tpc_addon_bright_r = "99",
        tpc_addon_bright_g = "255",
        tpc_addon_bright_b = "247",
        tpc_addon_bright_a = "99",
        tpc_addon_font_r = "124",
        tpc_addon_font_g = "124",
        tpc_addon_font_b = "124",
        tpc_addon_font_a = "255",
        tpc_highlight_dark_r = "66",
        tpc_highlight_dark_g = "249",
        tpc_highlight_dark_b = "239",
        tpc_highlight_dark_a = "255",
        tpc_highlight_bright_r = "61",
        tpc_highlight_bright_g = "255",
        tpc_highlight_bright_b = "245",
        tpc_highlight_bright_a = "255",
        tpc_highlight_font_r = "14",
        tpc_highlight_font_g = "113",
        tpc_highlight_font_b = "104",
        tpc_highlight_font_a = "255"
    },
    ["Menta"] = {
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_font_r = "135",
        tpc_gmod_font_g = "135",
        tpc_gmod_font_b = "135",
        tpc_gmod_font_a = "255",
        tpc_addon_dark_r = "85",
        tpc_addon_dark_g = "227",
        tpc_addon_dark_b = "87",
        tpc_addon_dark_a = "95",
        tpc_addon_bright_r = "99",
        tpc_addon_bright_g = "255",
        tpc_addon_bright_b = "102",
        tpc_addon_bright_a = "99",
        tpc_addon_font_r = "124",
        tpc_addon_font_g = "124",
        tpc_addon_font_b = "124",
        tpc_addon_font_a = "255",
        tpc_highlight_dark_r = "66",
        tpc_highlight_dark_g = "249",
        tpc_highlight_dark_b = "78",
        tpc_highlight_dark_a = "255",
        tpc_highlight_bright_r = "61",
        tpc_highlight_bright_g = "255",
        tpc_highlight_bright_b = "81",
        tpc_highlight_bright_a = "255",
        tpc_highlight_font_r = "14",
        tpc_highlight_font_g = "113",
        tpc_highlight_font_b = "20",
        tpc_highlight_font_a = "255"
    },
    ["Saara"] = {
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_font_r = "135",
        tpc_gmod_font_g = "135",
        tpc_gmod_font_b = "135",
        tpc_gmod_font_a = "255",
        tpc_addon_dark_r = "227",
        tpc_addon_dark_g = "227",
        tpc_addon_dark_b = "95",
        tpc_addon_dark_a = "85",
        tpc_addon_bright_r = "255",
        tpc_addon_bright_g = "255",
        tpc_addon_bright_b = "100",
        tpc_addon_bright_a = "99",
        tpc_addon_font_r = "124",
        tpc_addon_font_g = "124",
        tpc_addon_font_b = "124",
        tpc_addon_font_a = "255",
        tpc_highlight_dark_r = "249",
        tpc_highlight_dark_g = "249",
        tpc_highlight_dark_b = "66",
        tpc_highlight_dark_a = "255",
        tpc_highlight_bright_r = "255",
        tpc_highlight_bright_g = "255",
        tpc_highlight_bright_b = "62",
        tpc_highlight_bright_a = "255",
        tpc_highlight_font_r = "113",
        tpc_highlight_font_g = "113",
        tpc_highlight_font_b = "14",
        tpc_highlight_font_a = "255"
    },
    ["Tutti Frutti"] = {
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_font_r = "135",
        tpc_gmod_font_g = "135",
        tpc_gmod_font_b = "135",
        tpc_gmod_font_a = "255",
        tpc_addon_dark_r = "255",
        tpc_addon_dark_g = "83",
        tpc_addon_dark_b = "255",
        tpc_addon_dark_a = "110",
        tpc_addon_bright_r = "160",
        tpc_addon_bright_g = "97",
        tpc_addon_bright_b = "255",
        tpc_addon_bright_a = "83",
        tpc_addon_font_r = "110",
        tpc_addon_font_g = "110",
        tpc_addon_font_b = "110",
        tpc_addon_font_a = "255",
        tpc_highlight_dark_r = "227",
        tpc_highlight_dark_g = "136",
        tpc_highlight_dark_b = "235",
        tpc_highlight_dark_a = "255",
        tpc_highlight_bright_r = "235",
        tpc_highlight_bright_g = "155",
        tpc_highlight_bright_b = "243",
        tpc_highlight_bright_a = "255",
        tpc_highlight_font_r = "92",
        tpc_highlight_font_g = "25",
        tpc_highlight_font_b = "116",
        tpc_highlight_font_a = "255"
    },
    ["Wine"] = {
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_font_r = "135",
        tpc_gmod_font_g = "135",
        tpc_gmod_font_b = "135",
        tpc_gmod_font_a = "255",
        tpc_addon_dark_r = "255",
        tpc_addon_dark_g = "0",
        tpc_addon_dark_b = "0",
        tpc_addon_dark_a = "44",
        tpc_addon_bright_r = "255",
        tpc_addon_bright_g = "0",
        tpc_addon_bright_b = "0",
        tpc_addon_bright_a = "102",
        tpc_addon_font_r = "118",
        tpc_addon_font_g = "118",
        tpc_addon_font_b = "118",
        tpc_addon_font_a = "255",
        tpc_highlight_dark_r = "238",
        tpc_highlight_dark_g = "144",
        tpc_highlight_dark_b = "144",
        tpc_highlight_dark_a = "255",
        tpc_highlight_bright_r = "246",
        tpc_highlight_bright_g = "160",
        tpc_highlight_bright_b = "160",
        tpc_highlight_bright_a = "255",
        tpc_highlight_font_r = "116",
        tpc_highlight_font_g = "59",
        tpc_highlight_font_b = "59",
        tpc_highlight_font_a = "255"
    }
}
