--[[
    2020 Xalalau Xubilozo. MIT License
    https://xalalau.com/
--]]

TPC.defaultTools = {
    ["axis"] = true,
    ["ballsocket"] = true,
    ["elastic"] = true,
    ["hydraulic"] = true,
    ["motor"] = true,
    ["muscle"] = true,
    ["pulley"] = true,
    ["rope"] = true,
    ["slider"] = true,
    ["weld"] = true,
    ["winch"] = true,
    ["balloon"] = true,
    ["button"] = true,
    ["duplicator"] = true,
    ["dynamite"] = true,
    ["emitter"] = true,
    ["hoverball"] = true,
    ["lamp"] = true,
    ["light"] = true,
    ["nocollide"] = true,
    ["physprop"] = true,
    ["remover"] = true,
    ["thruster"] = true,
    ["wheel"] = true,
    ["eyeposer"] = true,
    ["faceposer"] = true,
    ["finger"] = true,
    ["inflator"] = true,
    ["camera"] = true,
    ["colour"] = true,
    ["material"] = true,
    ["paint"] = true,
    ["trails"] = true
}

TPC.options = {
    ["Default"] = {
        tpc_gmod_even_r = "255",
        tpc_gmod_even_g = "255",
        tpc_gmod_even_b = "255",
        tpc_gmod_even_a = "255",
        tpc_gmod_odd_r = "255",
        tpc_gmod_odd_g = "255",
        tpc_gmod_odd_b = "255",
        tpc_gmod_odd_a = "255",
        tpc_others_even_r = "255",
        tpc_others_even_g = "255",
        tpc_others_even_b = "255",
        tpc_others_even_a = "255",
        tpc_others_odd_r = "255",
        tpc_others_odd_g = "255",
        tpc_others_odd_b = "255",
        tpc_others_odd_a = "255"
    },
    ["Tutti Frutti"] = {
        tpc_gmod_even_r = "255",
        tpc_gmod_even_g = "255",
        tpc_gmod_even_b = "255",
        tpc_gmod_even_a = "255",
        tpc_gmod_odd_r = "255",
        tpc_gmod_odd_g = "255",
        tpc_gmod_odd_b = "255",
        tpc_gmod_odd_a = "255",
        tpc_others_even_r = "160",
        tpc_others_even_g = "97",
        tpc_others_even_b = "255",
        tpc_others_even_a = "67",
        tpc_others_odd_r = "255",
        tpc_others_odd_g = "116",
        tpc_others_odd_b = "255",
        tpc_others_odd_a = "85"
    },
    ["Saara"] = {
        tpc_gmod_even_r = "255",
        tpc_gmod_even_g = "255",
        tpc_gmod_even_b = "255",
        tpc_gmod_even_a = "255",
        tpc_gmod_odd_r = "255",
        tpc_gmod_odd_g = "255",
        tpc_gmod_odd_b = "255",
        tpc_gmod_odd_a = "255",
        tpc_others_even_r = "255",
        tpc_others_even_g = "255",
        tpc_others_even_b = "100",
        tpc_others_even_a = "50",
        tpc_others_odd_r = "255",
        tpc_others_odd_g = "255",
        tpc_others_odd_b = "100",
        tpc_others_odd_a = "50"
    },
    ["Menta"] = {
        tpc_gmod_even_r = "255",
        tpc_gmod_even_g = "255",
        tpc_gmod_even_b = "255",
        tpc_gmod_even_a = "255",
        tpc_gmod_odd_r = "255",
        tpc_gmod_odd_g = "255",
        tpc_gmod_odd_b = "255",
        tpc_gmod_odd_a = "255",
        tpc_others_even_r = "99",
        tpc_others_even_g = "255",
        tpc_others_even_b = "130",
        tpc_others_even_a = "50",
        tpc_others_odd_r = "99",
        tpc_others_odd_g = "255",
        tpc_others_odd_b = "130",
        tpc_others_odd_a = "50"
    }
}
