--[[
    2020 Xalalau Xubilozo. MIT License
    https://xalalau.com/
--]]

TPC.defaultTools = {
    ["axis"] = true,
    ["ballsocket"] = true,
    ["elastic"] = true,
    ["hydraulic"] = true,
    ["motor"] = true,
    ["muscle"] = true,
    ["pulley"] = true,
    ["rope"] = true,
    ["slider"] = true,
    ["weld"] = true,
    ["winch"] = true,
    ["balloon"] = true,
    ["button"] = true,
    ["duplicator"] = true,
    ["dynamite"] = true,
    ["emitter"] = true,
    ["hoverball"] = true,
    ["lamp"] = true,
    ["light"] = true,
    ["nocollide"] = true,
    ["physprop"] = true,
    ["remover"] = true,
    ["thruster"] = true,
    ["wheel"] = true,
    ["eyeposer"] = true,
    ["faceposer"] = true,
    ["finger"] = true,
    ["inflator"] = true,
    ["camera"] = true,
    ["colour"] = true,
    ["material"] = true,
    ["paint"] = true,
    ["trails"] = true
}

TPC.fakeToolsList = {
    { "GMod", "Axis" },
    { "GMod", "Ball Socket" },
    { "GMod", "Elastic" },
    { "GMod", "Hydraulic" },
    { "GMod", "Motor" },
    { "Others", "Custom Tool 1" },
    { "Others", "Custom Tool 2" },
    { "GMod", "Muscle" },
    { "GMod", "Pulley" },
    { "Others", "Custom Tool 3" },
    { "GMod", "Rope" },
    { "Others", "Custom Tool 4" },
    { "Others", "Custom Tool 5" },
    { "Others", "Custom Tool 6" },
    { "Others", "Custom Tool 7" },
}

TPC.defaultPreset = "Menta"

TPC.presets = {
    ["[Default]"] = {
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_others_bright_r = "255",
        tpc_others_bright_g = "255",
        tpc_others_bright_b = "255",
        tpc_others_bright_a = "255",
        tpc_others_dark_r = "255",
        tpc_others_dark_g = "255",
        tpc_others_dark_b = "255",
        tpc_others_dark_a = "255"
    },
    ["Tutti Frutti"] = {
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_others_bright_r = "160",
        tpc_others_bright_g = "97",
        tpc_others_bright_b = "255",
        tpc_others_bright_a = "67",
        tpc_others_dark_r = "255",
        tpc_others_dark_g = "116",
        tpc_others_dark_b = "255",
        tpc_others_dark_a = "85"
    },
    ["Saara"] = {
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_others_bright_r = "255",
        tpc_others_bright_g = "255",
        tpc_others_bright_b = "100",
        tpc_others_bright_a = "50",
        tpc_others_dark_r = "255",
        tpc_others_dark_g = "255",
        tpc_others_dark_b = "100",
        tpc_others_dark_a = "50"
    },
    ["Menta"] = {
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_others_bright_r = "99",
        tpc_others_bright_g = "255",
        tpc_others_bright_b = "130",
        tpc_others_bright_a = "50",
        tpc_others_dark_r = "99",
        tpc_others_dark_g = "255",
        tpc_others_dark_b = "130",
        tpc_others_dark_a = "50"
    },
    ["BSDO"] = {
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_others_bright_r = "96",
        tpc_others_bright_g = "228",
        tpc_others_bright_b = "255",
        tpc_others_bright_a = "67",
        tpc_others_dark_r = "115",
        tpc_others_dark_g = "208",
        tpc_others_dark_b = "255",
        tpc_others_dark_a = "85"
    },
    ["Wine"] = {
        tpc_gmod_bright_r = "255",
        tpc_gmod_bright_g = "255",
        tpc_gmod_bright_b = "255",
        tpc_gmod_bright_a = "255",
        tpc_gmod_dark_r = "255",
        tpc_gmod_dark_g = "255",
        tpc_gmod_dark_b = "255",
        tpc_gmod_dark_a = "255",
        tpc_others_bright_r = "255",
        tpc_others_bright_g = "0",
        tpc_others_bright_b = "0",
        tpc_others_bright_a = "115",
        tpc_others_dark_r = "255",
        tpc_others_dark_g = "0",
        tpc_others_dark_b = "0",
        tpc_others_dark_a = "52"
    }
}
